[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "epsSMASH"
description = "epsSMASH is a tool for the prediction of EPS biosynthetic gene clusters in bacterial genomes."
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  # temporarily this dependency points at a branch of a fork,
  # this will be replaced with github.com/antismash/antismash#master at some stage
  # however, specifing a particular version is much safer, e.g. "@7-1-0" instead of "#master"
  "antismash@ https://github.com/SJShaw/antismash/archive/refs/heads/custom_modules.zip",
]
requires-python = ">= 3.11"
authors = [
  {name = "AOHD", email = "aohd@bio.aau.dk"},
]
maintainers = [
  {name = "AOHD", email = "aohd@bio.aau.dk"},
]

[project.scripts]
epsSMASH = "epssmash:__main__.entrypoint"

[tool.setuptools.dynamic]
version = {attr = "epssmash.__version__"}

[tool.setuptools.package-data]
epssmash = [
    "detection/custom_detection/data/*.hmm",
    "detection/custom_detection/data/*.txt",
    "detection/custom_detection/data/individual_hmms/*.hmm",
    "detection/custom_detection/data/individual_hmms_loose_rules/*.hmm",
    "detection/custom_detection/cluster_rules/*.txt",
    "config/default.cfg",
    "outputs/html/gene_functions.tsv"
]