name: antismash_dependencies
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - hmmer2=2.3.2
  - hmmer=3.4
  - diamond=2.1.10
  - fasttree=2.1.11
  - prodigal=2.6.3
  - blast=2.5.0
  - muscle=5.1
  - glimmerhmm=3.0.4
  - python=3.11.10
